#include "TitleMenus.hpp"
#include "Binary.hpp"
#include <algorithm>
#include <cstdio>
namespace th09 {
namespace {
#include "TitleData.inc"
std::string field(const std::vector<u8>& data,u32 at,u32 count){std::string text;for(u32 n=0;n<count&&at+n<data.size()&&data[at+n];++n)text.push_back(char(data[at+n]));return text;}
}
void TitleMenus::load_replays(bool imported){
    replay_entries={};const auto load=[&](u32 index,std::string path){auto& entry=replay_entries[index];entry.path=std::move(path);std::vector<u8> bytes;if(!output.title_read_replay(entry.path.c_str(),bytes)||!entry.file.decode(bytes.data(),u32(bytes.size())))return;const auto& data=entry.file.data();entry.mode=data[0x1e4];entry.difficulty=data[0xd7];entry.versus=data[0x1e5];if(entry.mode>2||entry.difficulty>=5||entry.versus>4)return;bool round=false;for(u32 r=0;r<10;++r){const u32 a=entry.file.stream_offset(0,r),b=entry.file.stream_offset(1,r);if(a&&b&&data[a+6]<16&&data[b+6]<16)round=true;}if(!round)return;entry.name=field(data,0xce,9);entry.date=field(data,0xc4,10);entry.valid=true;};
    for(u32 n=0;n<25;++n){char name[40];std::snprintf(name,sizeof(name),"./replay/th9_%.2u.rpy",n+1);load(n,name);}
    if(imported){u32 index=25;for(const auto& name:output.title_imported_replays()){if(index>=50)break;if(name.size()!=14||name.rfind("th9_ud",0)!=0||name.substr(10)!=".rpy"||name.find_first_of("/\\")!=std::string::npos)continue;load(index++,"./replay/"+name);}}
}
bool TitleMenus::replays(){
    auto& s=state;const auto& in=input[2];if(!s.state){if(!s.load_frame){settings.game_flags&=~8u;if(s.previous_screen!=TitleScreen::replays&&!output.title_background("replay00.png"))return false;interrupt(22);s.selection=s.state=s.frames=0;s.description=-1;load_replays(true);s.replay_count=50;s.replay_scroll=0;}if(s.load_frame>7){s.state=1;s.frames=0;}}
    else if(s.state==1){const u16 keys=in.pressed|in.repeat;for(const auto pair:{std::pair<u16,i32>{16,-1},{32,1},{64,-25},{128,25}})if(keys&pair.first){output.title_sound(12);s.selection=(s.selection+pair.second+50)%50;s.frames=0;}
        if(in.pressed&10){output.title_sound(11);change(TitleScreen::main);s.selection=3;replay_entries={};return true;}
        if(in.pressed&0x1001){const auto& entry=replay_entries[s.selection];if(!entry.valid)output.title_sound(39);else{output.title_sound(10);s.replay_selected=s.selection;s.state=2;s.frames=s.selection=s.load_frame=0;while(s.selection<10&&!entry.file.stream_offset(0,s.selection))++s.selection;}}}
    else if(s.state==2){const auto& entry=replay_entries[s.replay_selected];if(navigate(s.selection,10,in)){const i32 direction=(in.pressed|in.repeat)&16?-1:1;for(i32 n=0;n<10&&!entry.file.stream_offset(0,s.selection);++n)s.selection=(s.selection+direction+10)%10;}
        if(in.pressed&10){s.state=1;s.frames=0;s.selection=s.replay_selected;}
        if(in.pressed&0x1001){settings.game_flags|=8;output.title_play_replay(entry.file,u32(s.selection),entry.path.c_str());replay_entries={};leaving=true;return false;}}
    tick();return true;
}
void TitleMenus::replay_save_slots(){load_replays(false);state.state=2;state.load_frame=state.selection=0;interrupt(22);advance();}
bool TitleMenus::save_replay(const char* path){if(!output.title_save_replay(path,replay_player_name.data())){error="Unable to save replay";return false;}return true;}
bool TitleMenus::replay_name(){
    auto& s=state;const auto& in=input[2];auto& records=output.title_records();
    if(!s.state){if(!s.load_frame){if(settings.game_flags&0x2000){change(TitleScreen::main);s.selection=0;return true;}if(automatic_replay_save){char path[48];i32 index=1;for(;index<1000;++index){std::snprintf(path,sizeof(path),"./replay/th9_udn%.3d.rpy",index);if(!output.title_replay_exists(path))break;}std::snprintf(path,sizeof(path),"./replay/th9_udn%.3d.rpy",index);std::copy_n(records.last_name.begin(),8,replay_player_name.begin());replay_player_name[8]=0;if(!save_replay(path))return false;change(TitleScreen::main);s.selection=0;s.return_to_versus=2;return true;}
        if(!output.title_background("replay00.png"))return false;interrupt(19);advance();s.selection=s.state=s.frames=0;s.description=-1;std::copy_n(records.last_name.begin(),8,replay_player_name.begin());replay_player_name[8]=0;if(result_mode==GameMode::versus)replay_save_slots();else{s.selection_base=125;s.selection_count=2;select(0,125,2);}}
        if(s.load_frame==8)s.state=1;}
    else if(s.state==1){const u16 keys=in.pressed|in.repeat;if(keys&(64|128)){output.title_sound(12);s.selection=1-s.selection;select(s.selection,s.selection_base,s.selection_count);}if(in.pressed&10){output.title_sound(11);if(!s.selection){s.selection=1;select(s.selection,s.selection_base,s.selection_count);}else{change(TitleScreen::main);s.selection=0;if(s.ranking_character>=0&&s.ranking_character<16&&s.ranking_slot>=0&&s.ranking_slot<5)std::copy_n(records.scores[s.ranking_character][settings.difficulty][s.ranking_slot].name.begin(),9,records.last_name.begin());return true;}}
        else if(in.pressed&0x1001){if(s.selection==1){output.title_sound(11);change(TitleScreen::main);s.selection=0;if(s.ranking_character>=0&&s.ranking_character<16&&s.ranking_slot>=0&&s.ranking_slot<5)std::copy_n(records.scores[s.ranking_character][settings.difficulty][s.ranking_slot].name.begin(),9,records.last_name.begin());return true;}replay_save_slots();}}
    else if(s.state==2&&s.load_frame>=6){if(navigate(s.selection,25,in))select(s.selection,s.selection_base,s.selection_count);if(in.pressed&10){output.title_sound(11);s.selection=s.load_frame=0;s.state=1;interrupt(19);advance();s.selection_base=125;s.selection_count=2;select(0,125,2);}else if(in.pressed&0x1001){output.title_sound(10);s.replay_selected=s.selection;s.selection=0;if(replay_entries[s.replay_selected].valid){s.state=3;interrupt(21);advance();s.selection_base=129;s.selection_count=2;select(0,129,2);}else{s.selection=95;s.state=4;interrupt(23);advance();}s.load_frame=0;std::copy_n(records.last_name.begin(),8,replay_player_name.begin());replay_player_name[8]=0;}}
    else if(s.state==3&&s.load_frame>=10){const u16 keys=in.pressed|in.repeat;if(keys&(64|128)){output.title_sound(12);s.selection=1-s.selection;select(s.selection,s.selection_base,s.selection_count);}if((in.pressed&10)||((in.pressed&0x1001)&&s.selection==1)){output.title_sound(11);s.state=2;s.selection=0;interrupt(22);advance();}else if(in.pressed&0x1001){output.title_sound(10);s.selection=95;s.state=4;interrupt(23);advance();}}
    else if(s.state==4&&s.load_frame>=10){move_name_cursor();if(in.pressed&0x1001){if(s.selection==95){output.title_sound(10);char path[40];std::snprintf(path,sizeof(path),"replay/th9_%.2d.rpy",s.replay_selected+1);if(!save_replay(path))return false;change(TitleScreen::main);s.selection=0;std::copy_n(replay_player_name.begin(),9,records.last_name.begin());return true;}replay_player_name[s.name_cursor]=s.selection==94?' ':name_characters[s.selection];output.title_sound(10);if(s.name_cursor<7)++s.name_cursor;else s.selection=95;s.frames=0;}
        if(in.pressed&10){output.title_sound(11);if(s.name_cursor==7&&replay_player_name[7]!=' ')replay_player_name[7]=' ';else if(s.name_cursor<1){s.selection=0;s.state=2;interrupt(22);advance();s.load_frame=0;}else replay_player_name[--s.name_cursor]=' ';s.frames=0;}}
    tick();return true;
}
void TitleMenus::replay_row(i32 index,const Vec3& p,u32 color,bool saving){const auto& entry=replay_entries[index];const char* name=entry.valid?entry.name.c_str():"--------";const char* date=entry.valid?entry.date.c_str():"--/--/--";char row[160];if(index<25)std::snprintf(row,sizeof(row),saving?"No.%.2d %.8s %8s":"No.%.2d %8s %8s",index+1,name,date);else{const std::string prefix=entry.valid&&entry.path.size()>=19?entry.path.substr(15,4):"user";std::snprintf(row,sizeof(row),"%.4s  %8s %8s",prefix.c_str(),name,date);}output.title_ascii(p,row,color,{1,1});}
void TitleMenus::draw_replays(){
    const auto& s=state;if(s.state==1){for(i32 n=0;n<50;++n)replay_row(n,{n<25?32.f:352.f,90.f+float(n%25)*13.f,0},n==s.selection?0xffffffff:0xff808080,false);}
    else if(s.state==2){const auto& entry=replay_entries[s.replay_selected];Vec3 position{s.replay_selected<25?32.f:352.f,float(s.replay_selected)*13.f+90.f,0};if(s.load_frame<10){position.x=(216.5f-position.x)*float(s.load_frame)*.1f+position.x;position.y=(160.f-position.y)*float(s.load_frame)*.1f+position.y;}else position={216.5f,160,0};replay_row(s.replay_selected,position,0xffffffff,false);char title[160];if(entry.mode==1)std::snprintf(title,sizeof(title),"%s",mode_labels[1]);else{const auto mode=entry.mode==0?mode_labels[0]:entry.versus<4?mode_labels[2+entry.versus]:ranking_labels[0];std::snprintf(title,sizeof(title),"%s  -%s-",mode,difficulty_labels[entry.difficulty]);}output.title_ascii({320.f-float(std::strlen(title))*4.5f,240,0},title,0xffffffff,{1,1});float y=270;for(u32 round=0;round<10;++round){const u32 a=entry.file.stream_offset(0,round),b=entry.file.stream_offset(1,round);if(!a||!b)continue;const auto& bytes=entry.file.data();const u32 first=bytes[a+6],second=bytes[b+6];if(first>=16||second>=16)continue;char row[64];std::snprintf(row,sizeof(row),"%.8s vs %.8s",character_labels[first],character_labels[second]);output.title_ascii({230,y,0},row,i32(round)==s.selection?0xffffffff:0xff808080,{1,1});y+=13;}}
}
void TitleMenus::draw_replay_name(){const auto& s=state;if(s.state==2){for(i32 n=0;n<25;++n)replay_row(n,{32,90.f+float(n)*13.f,0},n==s.selection?0xffffffff:0xff808080,true);}else if(s.state==3||s.state==4){Vec3 p{32,90.f+float(s.replay_selected)*13.f,0};if(s.load_frame<10){p.x=192.f*float(s.load_frame)*.1f+32.f;p.y=(224.f-p.y)*float(s.load_frame)*.1f+p.y;}else p={224,224,0};char row[96];std::snprintf(row,sizeof(row),"No.%.2d %.8s %8s",s.replay_selected+1,replay_player_name.data(),score_candidate.date.data());output.title_ascii(p,row,0xffffffff,{1,1});p.x+=float((s.name_cursor+6)*9);output.title_ascii(p,"_",0xffffffff,{1,1});if(s.state==4)draw_name_grid(236,320);}}
}
